### ISSUE TITLE
Logical type Date support

### ISSUE THREAD

**Issue by sergiutugulschi** [ch-robinson/dotnet-avro#133]
Currently getting 
`InvalidOperationException: No coercion operator is defined between types 'System.DateTime' and 'System.Int64' when trying to `serialize an object with DateTime property

in avro schema I have 
```
{
        "name": "BestBeforeDate",
        "type": [
          "null",
          {
            "type": "int",
            "logicalType": "date"
          }
        ],
        "default": null
      },
```
According to apache avro specs https://avro.apache.org/docs/1.8.0/spec.html#Date the date is mapped as int

**Comment by dstelljes** [comment]
The rationale for this is in [the documentation](https://engineering.chrobinson.com/dotnet-avro/internals/mapping#dates-and-times):

> .NET doesn’t include any types that match calendar date or time of day semantics, so no special mappings are provided for `"date"`, `"time-millis"`, and `"time-micros"`.

In other words, since `DateTime` includes a time component, Chr.Avro can’t map it to a `"date"` schema without making assumptions that might be incorrect (should the time be midnight GMT? midnight local? the current time?). If you deserialize to `int` instead of `DateTime`, you can do any necessary calculations or conversions in your application and ensure that the semantics are what you intend.
