### ISSUE TITLE
Consider update Confluent.Kafka to 1.6.x

### ISSUE THREAD

**Issue by eshepelyuk** [ch-robinson/dotnet-avro#138]
Hello

Currently `Confluent.Kafka` version is restricted to *>= 1.5.0 && < 1.6.0*. 
`Confluent.Kafka` 1.6 version was released, so it will be good to upgrade this library dependencies as well.

**Comment by dstelljes** [comment]
Thanks for opening the issue; we’ll increase the range with the 8.0.0 release. We were more lax in the past (4be4bd973c5558bf2b257138de7947465aea6609), but since Confluent.Kafka follows librdkafka versioning instead of semver, keeping the range too wide can break Chr.Avro.Confluent.

**Comment by eshepelyuk** [comment]
Hello @dstelljes 

Thnx for the reply, but is `Due by June 01, 2021` a real term of releasing 8.0.0 ?

**Comment by dstelljes** [comment]
It’s aspirational 🙂  One of the main goals of 8.x is schema builder support for nullable reference types, and because of the design of the type resolution framework, it’s taking awhile to get right. If we aren’t able to cut a major release by the end of the month, we’ll do a minor release with SDK/dependency version bumps.

**Comment by eshepelyuk** [comment]
Got it :))
Thnx

**Comment by rsaltrelli** [comment]
While you're at it, can you go to Confluent.Kafka 1.7?  Better yet, 1.*?

**Comment by dstelljes** [comment]
Thanks for your patience; the 7.1.0 release later today will target the 1.7.x versions of the Confluent clients. As mentioned above, we can't widen the version range to 1.x because the clients follow librdkafka versioning, not semver.
